Attribute VB_Name = "modComments"

'############################################################'
'#                  ChangeFormShape                         #'
'#                                                          #'
'#    ##################################################    #'
'#                                                          #'
'#  First: Please vote!                                     #'
'#                                                          #'
'#  Then:  Don't steal code!                                #'
'#                                                          #'
'#  Now:   Send feedback if you feel like it                #'
'#                                                          #'
'#    ##################################################    #'
'#                                                          #'
'#  Third Party Codes (TPCs)                                #'
'#                                                          #'
'#  1.                                                      #'
'#   clsGradient         - Rocky Clark                      #'
'#                         Kath-Rock Software               #'
'#                         http://www.kath-rock.com         #'
'#                                                          #'
'#  2.                                                      #'
'#   Form_Control        - Josef Lindinger                  #'
'#   Form_ControlPos       seliSoft Softwareentwicklung     #'
'#                         http://www.selisoft.com          #'
'#                                                          #'
'#  3.                                                      #'
'#   Resize Bars         - Munky                            #'
'#   (slight adjustments)  http://www.dnx-online.net        #'
'#                                                          #'
'#                                                          #'
'#  4.                                                      #'
'#   Picture-shaped-form - Doug Gaede                       #'
'#                         http://www.gaede.net             #'
'#                                                          #'
'#                                                          #'
'#    ##################################################    #'
'#                                                          #'
'#   Also some thanks to Steven Miller (Dependency Walker)  #'
'#  who tipped me off about MSDN ( msdn.microsoft.com ) and #'
'#  all the documented API-calls that can be found there.   #'
'#                                                          #'
'#    ##################################################    #'
'#                                                          #'
'#   I made this code because me and others may have some   #'
'#  use of it when we want to create nice-looking forms.    #'
'#   If you find it useful and want to use it in your       #'
'#  application, please let me know via e-mail or PSC.      #'
'#   Please vote, since I wish to win some nice stuff from  #'
'#  Exhedra                                                 #'
'#   Please keep using PSC ( www.pscode.com ) and keep your #'
'#  eyes on new codesamples from Mikael Nordfelth!          #'
'#                                                          #'
'#   THANK YOU GOOD PEOPLE AND KEEP WATCHING THE SKIES...   #'
'#  No, wait... I mean:                                     #'
'#  KEEP WATCHING PSC! (the truth is out there... on PSC)   #'
'#                                                          #'
'#   /Mikael Nordfelth                                      #'
'#    nordfelth@yahoo.com                                   #'
'#                                                          #'
'############################################################'

'  TPCs can be found at:
' 1. http://www.pscode.com/xq/ASP/txtCodeId.6154/lngWId.1/qx/vb/scripts/ShowCode.htm
' 2. http://www.pscode.com/xq/ASP/txtCodeId.27753/lngWId.1/qx/vb/scripts/ShowCode.htm
' 3. http://www.pscode.com/xq/ASP/txtCodeId.28774/lngWId.1/qx/vb/scripts/ShowCode.htm
' 4. http://www.pscode.com/xq/ASP/txtCodeId.14482/lngWId.1/qx/vb/scripts/ShowCode.htm

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'                                                                 '
' PS.                                                             '
'  The resize-bars can not be used properly in "Elliptic Mode"... '
'   You can control width/height, just not at the same time. =(   '
' DS.                                                             '
'                                                                 '
'  -------------------------------------------------------------  '
'                                                                 '
' For the frmPictureShape:                                        '
'  The transparency will only search for pixels that are EXACTLY  '
'   the same as the wanted color... Therefore you should not use  '
'   pics that are compressed, for instance JPG's.                 '
'                                                                 '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

 '''''''''''''''
'###         ###'
'###         ###'
'               '
'      ###      '
'      ###      '
'               '
' ##         ## '
'  ##       ##  '
'   #########   '
 '''''''''''''''
' Oh, man! This one is as cr*ppy as _
   a dog driving a lawnmower...
